# File: .github/workflows/repo-sync.yml
name: sync-blackmatrix7-ios_rule_script
on:
  schedule:
    - cron: '5 0,7,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync-blackmatrix7-ios_rule_script
jobs:
  pull-request:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: env.PAT
        with:
          #source_repo: "https://github.com/blackmatrix7/ios_rule_script.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
